### ISSUE TITLE
Don't assume that the otherwise block of a SwitchInt is right next to the current block

### ISSUE THREAD

**Issue by bjorn3** [softdevteam/yk#107]
While this happens to be true for MIR by change, it may not be true in all cases.

**Comment by vext01** [comment]
@bjorn3 is this still an issue? It looks like it's [correctly handled](https://github.com/softdevteam/yk/blob/cdc0bed49f77c7e8982bde4f15131ed425b8b458/internal_ws/yktrace/src/tir.rs#L352) in the TIR compiler?

**Comment by bjorn3** [comment]
It seems so.
