### ISSUE TITLE
Tracer choice should be automatic from -Ctracermode

### ISSUE THREAD

**Issue by vext01** [softdevteam/yk#119]
I was reviewing some yk code and realised that it's kind of odd that we offer the illusion of a runtime choice of tracer. We don't because you have to compile with the right `-C tracer=`.

I wonder if we should remove the option to `start_tracing` as it's kind of misleading.

**Comment by ltratt** [comment]
Is it misleading *now* or will it *always* be misleading?

**Comment by vext01** [comment]
It's certainly misleading now.

I can imagine a future where there is a runtime choice, but it involved two copies of any binary code that you'd want to trace. i.e. it's not the near future.

**Comment by ltratt** [comment]
Then my question is: do we want to rip it out now if we're going to add it back in one day? If it's really ugly to use now, maybe ripping it out is the right thing to do; if it's not that ugly, maybe leaving it in isn't going to do us much harm.

**Comment by vext01** [comment]
There is a compromise: crash if the user requests a kind of tracing they are not compiling for.

**Comment by ltratt** [comment]
Yes, that's fine with me!
