### ISSUE TITLE
Abstract bodyflags in SIR.

### ISSUE THREAD

**Issue by vext01** [softdevteam/yk#158]
* Make a function to check membership of a flag in the bitfield (thus allowing the underlying representation to change).
 * Maybe use the `bitflags` crate (but check if it's worth bringing in more deps. A bitfield is so simple, it may not be worth it).

**Comment by ltratt** [comment]
`bitvec` is solving a different problem than I think we have here. Anyway, I'll have a look at this one.

**Comment by bjorn3** [comment]
https://crates.io/crates/bitflags

**Comment by vext01** [comment]
> bitflags is solving a different problem than I think we have here.

Well, if you used bitflags (not bitvec!) your accessor would amount to `bitflags::contains(the_flag)`.

It pulls in a couple of other crates though. I'm not sure it's worth it for the gain :P
