### ISSUE TITLE
ykbh

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#220]
We have an internal crate `ykbh` and a test `ykbh.rs` -- but I'm not sure what `bh` stands for, and it's not documented. Can we clarify this somewhere? [Or, if I missed it, point me in the right direction ;)]

**Comment by bjorn3** [comment]
I guess bh stands for black hole.

**Comment by ltratt** [comment]
That was my assumption, but it isn't obvious to me that any of the tests actually invoke the blackhole code.

**Comment by vext01** [comment]
The tests invoke the blackholer via guard failure IIRC. @ptersilie ?

**Comment by ptersilie** [comment]
Yeah, I named it `ykbh` with the intention of naming the interpreter "blackhole interpreter". But then I ended up naming it `SIRInterpreter`. I thought the folder can still contain other blackholing related stuff, but I'm not so sure any more if there will be anything else apart from the interpreter.

**Comment by ltratt** [comment]
OK, let's have a think about the naming, as we'll need to get this consistent soon. FWIW, I'm not a big fan of "blackhole" for two reasons a) it doesn't give people any useful intuition about what it does b) it makes them think that it must be much more complicated conceptually than it actually is. But if that's the best name we can come up with for it, I can live with it, provided that we're consistent.

**Comment by vext01** [comment]
@ptersilie another thing on my todo, is to rename `SIRInterpreter` to `SirInterpreter` to be in line with other type names mentioning SIR and TIR.

**Comment by vext01** [comment]
Did we agree on "stop-gap" interpreter? If so, we should rename the crate and type.

**Comment by ltratt** [comment]
We agreed upon "stopgap" (no hyphen).

**Comment by vext01** [comment]
OK. I'll nip this in the bud now.
