### ISSUE TITLE
Layout of tests/src/yktrace.rs

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#221]
The structure of `tests/src/yktrace.rs` seems a bit odd, at least at first glance. There are top-level `#[test]`s, then a `mod tir` and more `#[test]`s inside it. I wondered if this is necessary, or whether we can simplify this?

**Comment by vext01** [comment]
It's on my todo lists to not categorise these tests by what module they were taken from, but by what they are testing.

The layout is just a leftover from the big refactoring, and we can certainly change it.
