### ISSUE TITLE
xtask prevents us running #[bench] targets?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#264]
If I try `cargo xtask bench` I am told:

```
xtask: the build system does not support the bench target
```

Is this insurmountable, or is there a way to get our existing `#[bench]` targets back up and running?

**Comment by bjorn3** [comment]
This may be as easy as adding "bench" as option to the same match arm as "test".

**Comment by ltratt** [comment]
Ah, I hadn't realised what that part of the code was doing. It's not *quite* as simple as adding `bench` to that arm, unfortunately, but I guess @vext01 will know the magic incantation to get this working again.

**Comment by vext01** [comment]
I expected 252d2187b2fa56069c6bc81127708fcbd817a789 to fix this, but for some reason we get:
```
error: optimisation cannot be enabled with a tracer
```

It looks like cargo is attempting to optimise the external workspace despite me forcing it off in `profile.bench`.

I'm confused. Any ideas @bjorn3?

**Comment by bjorn3** [comment]
I don't know what the problem is.
