### ISSUE TITLE
Non-testing code in test_api.rs

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#277]
`ykshim_client/src/test_api.rs` has this comment:

```
//! The testing API client to ykshim.
```

but I think there are two potential problems:

1. I think the code in this file (and its sister "testing" files) is always compiled even in non-testing mode?
2. There appear to be non-testing functions (e.g. `compile_tir_trace`) in there too?

Warning: I might have grossly misunderstood this. However, if I am roughly right, it's a bit annoying: I'd like to make ` __ykshimtest_interpret_body` testing only (so that I can then make `set_interp_ctx` be `#[cfg(test)]` or similar) but at the moment that leads to a mess of linking errors.

**Comment by bjorn3** [comment]
> I think the code in this file (and its sister "testing" files) is always compiled even in non-testing mode?

`#[cfg(test)]` only applies to the crate being tested, never to any of it's dependencies even without the workspace setup yorick is using.

> There appear to be non-testing functions (e.g. compile_tir_trace) in there too?

That one is only necessary for testing. The regular api only does sir -> compiled code, not tir -> compiled code.

**Comment by ltratt** [comment]
Perhaps we need to have something like a `test` feature that only enables features when we want a testing mode? The problem at the moment is that we're unable to be clear which parts of different sub-libraries is only intended for test purposes and which is needed for non-testing. e.g. `set_interp_ctx` is currently part of the public API which is probably not what we want to communicate to users.

**Comment by ltratt** [comment]
It seems like `features` might partly work, but perhaps not all the way. Consider this diff:

```
diff --git internal_ws/ykshim/Cargo.toml internal_ws/ykshim/Cargo.toml
index 5783e1f..a3b1a77 100644
--- internal_ws/ykshim/Cargo.toml
+++ internal_ws/ykshim/Cargo.toml
@@ -14,3 +14,6 @@ yksg = { path = "../yksg" }
 ykcompile = { path = "../ykcompile" }
 ykpack = { path = "../ykpack" }
 yktrace = { path = "../yktrace" }
+
+[features]
+testing = []
diff --git internal_ws/ykshim/src/lib.rs internal_ws/ykshim/src/lib.rs
index 1f0ce8c..b8eb335 100644
--- internal_ws/ykshim/src/lib.rs
+++ internal_ws/ykshim/src/lib.rs
@@ -3,6 +3,7 @@
 //! For more information, see this section in the documentation:
 //! https://softdevteam.github.io/ykdocs/tech/yk_structure.html
 
+#[cfg(feature = "testing")]
 mod test_api;
 
 use std::ffi::{c_void, CString};
diff --git tests/Cargo.toml tests/Cargo.toml
index 917a711..dcecfc1 100644
--- tests/Cargo.toml
+++ tests/Cargo.toml
@@ -6,7 +6,7 @@ edition = "2018"
 
 [dependencies]
 fm = "0.2.0"
-ykshim_client = { path = "../ykshim_client" }
+ykshim_client = { path = "../ykshim_client", features=["testing"] }
 libc = "0.2.82"
 regex = "1.4.3"
 ykrt = { path = "../ykrt" }
diff --git ykshim_client/Cargo.toml ykshim_client/Cargo.toml
index 949eca2..9e3156e 100644
--- ykshim_client/Cargo.toml
+++ ykshim_client/Cargo.toml
@@ -7,3 +7,6 @@ license = "Apache-2.0 OR MIT"
 
 [dependencies]
 libc = "0.2.82"
+
+[features]
+testing = []
diff --git ykshim_client/src/lib.rs ykshim_client/src/lib.rs
index 7d7dd89..ebc2091 100644
--- ykshim_client/src/lib.rs
+++ ykshim_client/src/lib.rs
@@ -16,7 +16,9 @@ use std::marker::PhantomData;
 use std::os::raw::c_char;
 use std::{mem, ptr};
 
+#[cfg(feature = "testing")]
 mod test_api;
+#[cfg(feature = "testing")]
 pub use test_api::*;
 
 pub(crate) type RawCompiledTrace = c_void;
```

This compiles and tests OK and reduces the amount of code that's exposed during `cargo xtask test`.

However if I try and do something similar to `internal_ws/ykshim/src/lib.rs` I get into trouble because `xtask/src/main.rs` does this:

```
                // `cargo test` in the internal workspace won't build libykshim.so, so we have
                // to force-build it to avoid linkage problems for the external workspace.
                if target == "test" {
                    run_action(Workspace::Internal, "build", &[]);
                }
```

In other words, as far as I can see, we have a situation where building for `cargo xtask test` also builds some parts of the repository as "normal" `cargo xtask build`? If that's the case, it would be good to think of some way of conditionally compiling some code *only* when we're in testing mode overall. How that should be done is above my current pay grade :)

**Comment by ltratt** [comment]
Fixed by https://github.com/softdevteam/yk/pull/278.
