### ISSUE TITLE
Workspace and library names

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#311]
At the moment we have this naming scheme:

```
          External Workspace                Internal Workspace
+------------------------------------+ +-----------------------------+
| Interpreter +                      | |                             |
|             |                      | |                             |
|             +----> ykshim_client +----> yk_shim +----> JIT runtime |
|             |                      | |                             |
|       Tests +                      | |                             |
+------------------------------------+ +-----------------------------+
```

I find the "shim" and, in particular, "shim_client" parts really confusing, partly because a shim is something used to fill a gap or keep objects apart a certain amount. That's not really what's going on here and it taxes my poor little brain.

Before I go any further, let me acknowledge that any effort put into renaming things risks going horribly wrong. So I'm going to make a concrete suggestion, but if you think it's completely bonkers, then let's not obsess about this.

My first suggestion is that we consider renaming the workspaces, as it's not entirely clear to me what they're internal/external to. https://softdevteam.github.io/ykdocs/tech/yk_structure.html describes them as such:

> To this end, we have two Rust workspaces in the yk repo: the "internal" (optimised) workspace, and the "external" (unoptimised) workspace.

That suggests that we actually know more descriptive names for them already: optimised and unoptimised. Why don't we call them `opt` and `unopt` and be done with it?

My second suggestion is around ykshim. I suggest it's rather acting as a "bridge" and that neither side is a client or server. That makes me think that `opt_bridge` and `unopt_bridge` (or something along those lines) might make things clearer?

My final, bonus, suggestion is that we might want to reconsider the directory structure. At the moment the `internal_ws`/`opt` workspace has its own directory but the "external"/`unopt` doesn't. That means that we have some crates at the top-level and some in a directory one-level deep which makes some (incorrectly) feel more "important" than others. I think there are two separate solutions to this:

1. We put the external/unopt parts in their own directory.
2. We put all crates at the top-level and then have two workspace directories (e.g. `unopt`/`opt`) whose `Cargo.toml`'s point back to the top-level directories.

I *think* I prefer the latter approach (assuming that my reading [of the RFC](https://rust-lang.github.io/rfcs/1525-cargo-workspace.html) is correct and it's possible) as it means we can mostly stop thinking about the separate workspaces.

Thoughts and comments welcome!

**Comment by bjorn3** [comment]
> Why don't we call them opt and unopt and be done with it?

In the future a compiler could potentially optimize the external workspace and the user application too, but leave just enough optimizations disabled for accurate hardware tracing.

> My second suggestion is around ykshim. I suggest it's rather acting as a "bridge" and that neither side is a client or server. That makes me think that opt_bridge and unopt_bridge (or something along those lines) might make things clearer?

💯

**Comment by ltratt** [comment]
>  In the future a compiler could potentially optimize the external workspace and the user application too, but leave just enough optimizations disabled for accurate hardware tracing.

Point taken. Maybe `traceable` and `untraceable` might be better, as it doesn't commit us to opt/unopt.

**Comment by vext01** [comment]
> That suggests that we actually know more descriptive names for them already: optimised and unoptimised.

Also, since merging my last PR, the internal workspace may not be optimised. Only if `--release` is passed.

How about "internal" and "user-facing".

**Comment by vext01** [comment]
> opt_bridge and unopt_bridge

opt aside, I find these more confusing than what we have. Is `opt_bridge` a bridge to or from the optimised side?

> hierarchy

I'd be OK with a hierarchy like this:
```
yk
\-- internal_ws
\-- user_ws
```

As this might help to remove some of the hacks we had to insert to stop cargo walking up the filesystem.

Note that any renaming will be fiddly, as the build system is a nightmare! But that's not a good reason not to think about a rename.

**Comment by ltratt** [comment]
The problem with "user" and "internal" is it begs the question: why did we split them that way? It seems like a lot of effort! It feels like it'll be clearer to me if they're named after the cause of their split. At first I thought that was opt/unopt but actually traceable/untraceable is the real reason for the split, so that seems like the better naming scheme. Besides, if we do the directory hack with `../` links, most people won't even really need to know why there's two directories solely consisting of `Cargo.toml`!

**Comment by vext01** [comment]
> traceable/untraceable

I find that "OK" (perhaps 'traced/untraced' is better on account of being less of a mouthful).

But I don't think anything we have proposed so far is significantly better than 'internal/external' (or 'internal/main').

> it's not entirely clear to me what they're internal/external to.

I've been thinking about this ^.

Suppose I were to put an unidentified object on the table in front of you and say "shall we look at its internals?", I think you'd know what I meant. And "software internals" is familiar terminology to most programmers. So when @bjorn3 proposed [separately compiling the "internals"](https://github.com/softdevteam/yk/pull/205), I knew exactly what was meant because it was intuitive.

@ptersilie, what do you think of all of this?

**Comment by ltratt** [comment]
*If* my suggestion of having this directory structure:

```
external/
  - Cargo.toml
internal/
  - Cargo.toml
tests/
ykcompile/
ykpack/
ykrt/
yksg/
ykshim/
ykshim_client/
yktrace/
ykview/
```

makes sense to people then I think it makes much less difference what we call the workspaces, as they no longer make much difference when you're editing files.

**Comment by vext01** [comment]
I'd imagined that you meant something like this:
```
xtask/
external/
  ykrt/
  tests/
internal/
  ykcompile/
  ykpack/
  yksg/
  ykshim/
  ykshim_client/
  yktrace/
  ykview/
```

Mixing crate members from different workspaces at the top-level is going to get confusing.

**Comment by ltratt** [comment]
That structure also works, but then I do think that the names become important. That's why I was wondering if putting all the crates at the top-level might be better. It may, however, be a very bad idea on my part!

**Comment by vext01** [comment]
> That structure also works, but then I do think that the names become important.

> makes much less difference what we call the workspaces, as they no longer make much difference when you're editing files.

There's something implicit going on here that I don't yet have a grasp on.

When you want to edit `internal/yktrace/lib.rs` for example, what is it about the name of the workspace (internal) that makes a difference to editing? Don't you just kick up fzf and type something like `yktlib`?

**Comment by ltratt** [comment]
> Don't you just kick up fzf and type something like yktlib?

Yes, but I still get confused. Admittedly part of that is perhaps because we have duplicate leaf names:

```
./internal_ws/ykshim/src/test_api.rs
./ykshim_client/src/test_api.rs
./internal_ws/yktrace/src/tir.rs
./tests/src/tir.rs
```

Differentiating those is probably a useful task, but for another PR.

I guess my confusion is partly because at the moment I see "internal_ws" coming up all the time, except when it doesn't. Maybe this is OCD on my part, but I *think* @ptersilie also felt a bit similarly to me (or maybe, like me, it was actually ykshim/ykshim_client that he found more confusing).

**Comment by vext01** [comment]
> duplicate leaf names

I agree that this is annoying, but I'd also argue that that's a separate matter from the naming of the workspace.

[FWIW, I'm not against trying to de-duplicate them, but the duplication is to some degree inevitable. Most of duplication is due to duality between components and this often caused by the need to separate tests out into a different workspace so that they can be traced]

**Comment by ptersilie** [comment]
I agree on the duplicate leaf nodes and the ykshim/ykshim_client problems. I still sometimes get confused which file I want to open even when using `fzf`. I'm not sure I like the "everything at the top level" idea, as I'll then get confused why there are two folders with just `Cargo.toml` files in there. But I'm happy with renaming the workspaces to "traceable/untraceable". I think that's quite clear.

**Comment by vext01** [comment]
OK, so I'm out-voted on the workspace naming.

@ptersilie is "traced/untraced" also OK for you? I find those names easier to say.

**Comment by ptersilie** [comment]
> @ptersilie is "traced/untraced" also OK for you? I find those names easier to say.

Sure, no preference on that, as long as the name makes the separation clear.

**Comment by ltratt** [comment]
This is now part of master.
