### ISSUE TITLE
Incorrect assert in reg_alloc_always_on_stack?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/yk#315]
The `reg_alloc_always_on_stack` test has this chunk:

```
    // Small types, like `u8`, can easily fit in a register, but if a local decl is referenced
    // at some point in its live range then the allocator will put it directly onto the stack
    // (even if registers are available).
    assert!(dbg!(tc.local_to_location_str(Local(3))).starts_with("Mem("));
```

The comment makes sense *but* I can't see anywhere where a reference is taken to any local (let alone `Local(3)`) so I think the `assert` is incorrect. I have made random changes to the compiler that trigger this `assert` -- I don't *think* my changes are related, but they probably change something non-deterministic (e.g. variable ordering in a hashset perhaps?) that cause this to fail.

**Comment by ptersilie** [comment]
Looks like @vext01 wrote these, so he's probably in a better position to comment than me.

**Comment by ptersilie** [comment]
Ah, after reading https://github.com/softdevteam/yk/issues/316 I see what's going on. Since the second argument to `LocalDecl::new` is true, this means the local will be referenced at a later point, which means it needs to land on the stack.

**Comment by ltratt** [comment]
Ah, I see. That suggests I've got something wrong somewhere! I suspect I'll close this issue.

**Comment by ptersilie** [comment]
Maybe wait for @vext01 to confirm?

**Comment by vext01** [comment]
Yes, the u8 is forced to the stack as it is referenced at some point in the SIR graph.

By the way, there's an inaccurate comment in this test:
```
// In a TIR trace, the first two decls are a unit and the interpreter context...
```

It's not longer a unit as the interp_step now has a return value.

**Comment by ltratt** [comment]
> By the way, there's an inaccurate comment in this test:

Can I leave you to raise a PR for that? Otherwise I'm closing this PR as probably being caused my something stupid I did elsewhere that just so happened to trigger a problem in this test.
