### ISSUE TITLE
Examples or documentation on how to use yorick? 

### ISSUE THREAD

**Issue by playXE** [softdevteam/yk#88]

**Comment by vext01** [comment]
Hi,

Thanks for the interest!

Yorick is in early stages of development, and isn't really ready for mainstream consumption.

We are currently implementing types in our IR and we have yet to implement the JIT merge point and a black-holing mechanism. I think only once these bits are implemented will we have something we can realistically show as a prototype, and that'd be the time to document the system more thoroughly.

I'm happy to answer any questions that you may have about the system though :)

**Comment by playXE** [comment]
Thanks for answer! I've got another few questions :)
1) Will it be possible to use any GC implementation with yorick? 
2) Will this library/compiler provide something like LLVM stackmaps for GC?

**Comment by ltratt** [comment]
At least at the moment, we'll probably be largely GC-agnostic, so one can use whatever GC one wishes. At some point, I expect that to get better optimisations working we'll need to know something more about the GC, at which point it might become semi- or fully-hardcoded. It's a bit hard to know at the moment.

We're separately working on a GC solution and as part of that we've spent quite a bit of time getting to grip with stackmaps. @jacob-hughes is our local GC expert. There are quite a lot of challenges with Rust + GC, so we're not going to get a perfect solution overnight.

Out of curiosity, what brought you to this repo? Are you working on something similar? As you can see, we do everything in the open, so we're always willing to talk!

**Comment by playXE** [comment]
@ltratt I work on [WaffleLink](https://github.com/jazz-lang/WaffleLink) runtime for dynamically typed languages, there is already method baseline jit and optimizing tier is planned in future but I also would like to have tracing JIT for users that need tracing jit instead of method JIT

**Comment by ltratt** [comment]
Very cool stuff! I have a suspicion that we're working to a slower timetable than you would find comfortable, partly because the "meta" bit of "meta-tracing" is where a lot of the difficulty lies for us. However, if any of the components we're building look useful, you should feel free to make use of them! We're always available to discuss possibilities!

**Comment by playXE** [comment]
Thanks for help! Can I somehow contribute to this project? (I don't know anything about internals of meta-tracing compilers sadly )

**Comment by ltratt** [comment]
Yes, we are very happy for people to contribute! Please send me an email at laurie@tratt.net and we can take things from there :)

**Comment by playXE** [comment]
@ltratt I've sent you a message from adel.prokurov@gmail.com , still waiting :D

**Comment by ltratt** [comment]
Hello! Unfortunately I haven't got an email from you: my mail server doesn't have an email from that address in its logs so I guess it got lost before my server :/ Can you try resending please?

**Comment by vext01** [comment]
Can we close this issue?

We have some limited documentation here:
https://softdevteam.github.io/ykdocs/

In terms of examples, the tests are probably the best we have at this point, but we hope to have a proper interpreter using Yorick soon.

**Comment by ltratt** [comment]
Yes, closing.
